services:
  moria:
    image: ghcr.io/isyuricunha/return-to-mortia:latest
    container_name: return-to-moria
    restart: unless-stopped
    user: "${PUID:-1000}:${PGID:-1000}"
    env_file:
      - .env
    ports:
      - "7777:7777/udp"
    volumes:
      - ./data:/mnt/server
